insert into author (name, gender, country) values ('Harland Tasseler', 'M', 'Poland');
insert into author (name, gender, country) values ('Cyrillus Pow', 'M', 'Mali');
insert into author (name, gender, country) values ('Randa Chater', 'F', 'China');
insert into author (name, gender, country) values ('Gannie Voelker', 'M', 'Greece');
insert into author (name, gender, country) values ('Liv Gerold', 'F', 'China');
insert into author (name, gender, country) values ('Alica Sambrook', 'F', 'Indonesia');
insert into author (name, gender, country) values ('Ramona Marciskewski', 'F', 'Philippines');
insert into author (name, gender, country) values ('Cobby Omond', 'M', 'China');
insert into author (name, gender, country) values ('Leslie Christensen', 'F', 'Yemen');
insert into author (name, gender, country) values ('Friedrick Lerven', 'M', 'Indonesia');
insert into author (name, gender, country) values ('Hube de Clerc', 'M', 'Tanzania');
insert into author (name, gender, country) values ('Dannye Jacquemot', 'F', 'Russia');
insert into author (name, gender, country) values ('Zeke Valois', 'M', 'Tajikistan');
insert into author (name, gender, country) values ('Lacy Snelle', 'F', 'Indonesia');
insert into author (name, gender, country) values ('Stacee Skellern', 'M', 'Russia');
insert into author (name, gender, country) values ('Lilyan Joselovitch', 'F', 'China');
insert into author (name, gender, country) values ('Hasty Siemantel', 'M', 'Honduras');
insert into author (name, gender, country) values ('Melisandra Jeanin', 'F', 'China');
insert into author (name, gender, country) values ('Corinne Heineke', 'F', 'Sweden');
insert into author (name, gender, country) values ('Dallis Gallico', 'M', 'China');
insert into author (name, gender, country) values ('Peg Ellicombe', 'F', 'Indonesia');
insert into author (name, gender, country) values ('Ellette Webber', 'F', 'China');
insert into author (name, gender, country) values ('Debee Cullrford', 'F', 'Mauritania');
insert into author (name, gender, country) values ('Marigold Simpkin', 'F', 'Indonesia');
insert into author (name, gender, country) values ('Orin Howbrook', 'M', 'Kazakhstan');
insert into author (name, gender, country) values ('Bryna Valois', 'F', 'China');
insert into author (name, gender, country) values ('Jon Neem', 'M', 'Portugal');
insert into author (name, gender, country) values ('Renae Gaskamp', 'F', 'France');
insert into author (name, gender, country) values ('Dur Olyunin', 'M', 'Bosnia and Herzegovina');
insert into author (name, gender, country) values ('Krissie Ashman', 'F', 'Indonesia');
insert into author (name, gender, country) values ('Andre Vannucci', 'M', 'Cameroon');
insert into author (name, gender, country) values ('Tonia Boothebie', 'F', 'Slovenia');
insert into author (name, gender, country) values ('Care Dalley', 'M', 'Croatia');
insert into author (name, gender, country) values ('Clarke Haville', 'M', 'Bosnia and Herzegovina');
insert into author (name, gender, country) values ('Violette Sutcliffe', 'F', 'Palestinian Territory');
insert into author (name, gender, country) values ('Sandor Simester', 'M', 'Albania');
insert into author (name, gender, country) values ('Reggie MacNally', 'F', 'Russia');
insert into author (name, gender, country) values ('Dulcy Pinyon', 'F', 'Sweden');
insert into author (name, gender, country) values ('Suzanne de Keyser', 'F', 'Slovenia');
insert into author (name, gender, country) values ('Dodie Kinastan', 'F', 'France');
insert into author (name, gender, country) values ('Etan Bowater', 'M', 'Malawi');
insert into author (name, gender, country) values ('Alejandro Guilliatt', 'M', 'Croatia');
insert into author (name, gender, country) values ('Drucie Briat', 'F', 'Bolivia');
insert into author (name, gender, country) values ('Johanna Smullin', 'F', 'Ukraine');
insert into author (name, gender, country) values ('Pasquale Draysey', 'M', 'Sweden');
insert into author (name, gender, country) values ('William Barrie', 'M', 'Morocco');
insert into author (name, gender, country) values ('Bidget Phillcox', 'F', 'Norway');
insert into author (name, gender, country) values ('Cirstoforo De Michele', 'M', 'Indonesia');
insert into author (name, gender, country) values ('Isaac Gainsburgh', 'M', 'Ukraine');
insert into author (name, gender, country) values ('Lilia Braganza', 'F', 'Slovenia');
insert into author (name, gender, country) values ('Nathanial Fisbburne', 'M', 'United Kingdom');
insert into author (name, gender, country) values ('Tremayne Henrichsen', 'M', 'China');
insert into author (name, gender, country) values ('Gertie Redholls', 'F', 'Indonesia');
insert into author (name, gender, country) values ('Giorgi Waddie', 'M', 'Libya');
insert into author (name, gender, country) values ('Katha Siss', 'F', 'China');
insert into author (name, gender, country) values ('Brnaba Candish', 'M', 'Ethiopia');
insert into author (name, gender, country) values ('Edna Rault', 'F', 'Tanzania');
insert into author (name, gender, country) values ('Emerson Rubinowitsch', 'M', 'Mexico');
insert into author (name, gender, country) values ('Nickey Percy', 'M', 'Sweden');
insert into author (name, gender, country) values ('Hillary Wrefford', 'F', 'Brazil');
insert into author (name, gender, country) values ('Yoko Isgar', 'F', 'Czech Republic');
insert into author (name, gender, country) values ('Shela Gocher', 'F', 'France');
insert into author (name, gender, country) values ('Mia Schechter', 'F', 'Ethiopia');
insert into author (name, gender, country) values ('Marlane Baumler', 'F', 'Russia');
insert into author (name, gender, country) values ('Iver Lamminam', 'M', 'Uruguay');
insert into author (name, gender, country) values ('Kalil Ferrulli', 'M', 'Indonesia');
insert into author (name, gender, country) values ('Shanta Rebichon', 'F', 'Philippines');
insert into author (name, gender, country) values ('Sam Hekkert', 'F', 'Russia');
insert into author (name, gender, country) values ('Sabrina Ceschini', 'F', 'Russia');
insert into author (name, gender, country) values ('Chery Arlidge', 'F', 'Russia');
insert into author (name, gender, country) values ('Gerianne Jakel', 'F', 'France');
insert into author (name, gender, country) values ('Reginald Ricardet', 'M', 'France');
insert into author (name, gender, country) values ('Bathsheba Segrott', 'F', 'Brazil');
insert into author (name, gender, country) values ('Roselia Acock', 'F', 'Thailand');
insert into author (name, gender, country) values ('Matthus Woof', 'M', 'France');
insert into author (name, gender, country) values ('Armstrong Leamy', 'M', 'South Africa');
insert into author (name, gender, country) values ('Wye Dudman', 'M', 'Russia');
insert into author (name, gender, country) values ('Morten Blurton', 'M', 'United States');
insert into author (name, gender, country) values ('Lexie Hopfer', 'F', 'China');
insert into author (name, gender, country) values ('Germain Cardwell', 'M', 'Poland');
insert into author (name, gender, country) values ('Katey Jorge', 'F', 'Portugal');
insert into author (name, gender, country) values ('Vanya Dilleston', 'M', 'Japan');
insert into author (name, gender, country) values ('Rickert Sabine', 'M', 'Kyrgyzstan');
insert into author (name, gender, country) values ('Vi Duggen', 'F', 'Indonesia');
insert into author (name, gender, country) values ('Jammal Mars', 'M', 'Guatemala');
insert into author (name, gender, country) values ('Kilian Patty', 'M', 'China');
insert into author (name, gender, country) values ('Marcos Gillice', 'M', 'Nigeria');
insert into author (name, gender, country) values ('Caryl Thrower', 'F', 'Bulgaria');
insert into author (name, gender, country) values ('Joletta Gabby', 'F', 'Thailand');
insert into author (name, gender, country) values ('Jerrilyn Scullin', 'F', 'China');
insert into author (name, gender, country) values ('Thom Lawee', 'M', 'China');
insert into author (name, gender, country) values ('Sauveur Whistan', 'M', 'Vietnam');
insert into author (name, gender, country) values ('Sherwynd Moriarty', 'M', 'China');
insert into author (name, gender, country) values ('Kara Osmond', 'F', 'Poland');
insert into author (name, gender, country) values ('Rozella Limpricht', 'F', 'China');
insert into author (name, gender, country) values ('Dylan Bonnavant', 'M', 'Indonesia');
insert into author (name, gender, country) values ('Dorise Urwin', 'F', 'Micronesia');
insert into author (name, gender, country) values ('Jessey Tiltman', 'M', 'Portugal');
insert into author (name, gender, country) values ('Simmonds Hirsch', 'M', 'Cameroon');
insert into author (name, gender, country) values ('Marquita Bowland', 'F', 'China');
insert into author (name, gender, country) values ('Carter De Angelo', 'M', 'Sweden');
insert into author (name, gender, country) values ('Brien Peaddie', 'M', 'Philippines');
insert into author (name, gender, country) values ('Barbara-anne Caddell', 'F', 'Poland');
insert into author (name, gender, country) values ('Vinny Sommer', 'F', 'United States');
insert into author (name, gender, country) values ('Jakie Whild', 'M', 'Estonia');
insert into author (name, gender, country) values ('Ardis Remer', 'F', 'Argentina');
insert into author (name, gender, country) values ('Mayor Pinnion', 'M', 'China');
insert into author (name, gender, country) values ('Vinnie Dowles', 'F', 'China');
insert into author (name, gender, country) values ('Neville Benzie', 'M', 'Indonesia');
insert into author (name, gender, country) values ('Arabele Ollington', 'F', 'Poland');
insert into author (name, gender, country) values ('Hersh Kermode', 'M', 'Greece');
insert into author (name, gender, country) values ('Margo Lindenbluth', 'F', 'Poland');
insert into author (name, gender, country) values ('Catie Giggs', 'F', 'Brazil');
insert into author (name, gender, country) values ('Yolane McGahern', 'F', 'China');
insert into author (name, gender, country) values ('Hobie Puddicombe', 'M', 'Malaysia');
insert into author (name, gender, country) values ('Christiano Kidston', 'M', 'Indonesia');
insert into author (name, gender, country) values ('Bobby Fritschel', 'M', 'Argentina');
insert into author (name, gender, country) values ('Keenan Janusz', 'M', 'Lithuania');
insert into author (name, gender, country) values ('Jacqueline Barritt', 'F', 'Finland');
insert into author (name, gender, country) values ('Bald Cowlin', 'M', 'Indonesia');
insert into author (name, gender, country) values ('Farrah Kleinsinger', 'F', 'South Africa');
insert into author (name, gender, country) values ('Barb Carlsson', 'F', 'Canada');
insert into author (name, gender, country) values ('Sarena Carnell', 'F', 'Ukraine');
insert into author (name, gender, country) values ('Tamera Vernon', 'F', 'China');
insert into author (name, gender, country) values ('Danni Scobbie', 'F', 'Brazil');
insert into author (name, gender, country) values ('Cristabel Spens', 'F', 'Brazil');
insert into author (name, gender, country) values ('Rudolfo Fennelow', 'M', 'China');
insert into author (name, gender, country) values ('Dallis Binden', 'M', 'Indonesia');
insert into author (name, gender, country) values ('Terrance Meadway', 'M', 'Poland');
insert into author (name, gender, country) values ('Melina Grinsdale', 'F', 'Mongolia');
insert into author (name, gender, country) values ('Brion Bugge', 'M', 'France');
insert into author (name, gender, country) values ('Wilton Kunrad', 'M', 'China');
insert into author (name, gender, country) values ('Kristos McIlvaney', 'M', 'Indonesia');
insert into author (name, gender, country) values ('Ramonda Milella', 'F', 'Netherlands');
insert into author (name, gender, country) values ('Nels Attwater', 'M', 'Philippines');
insert into author (name, gender, country) values ('Darrick Woollcott', 'M', 'Philippines');
insert into author (name, gender, country) values ('Claretta Aldridge', 'F', 'Canada');
insert into author (name, gender, country) values ('Joanie Dowthwaite', 'F', 'Greece');
insert into author (name, gender, country) values ('Dallas Anthony', 'M', 'China');
insert into author (name, gender, country) values ('Cassie Desson', 'M', 'China');
insert into author (name, gender, country) values ('Daven Bulter', 'M', 'Canada');
insert into author (name, gender, country) values ('Clifford MacVagh', 'M', 'Portugal');
insert into author (name, gender, country) values ('Robbin Trank', 'F', 'France');
insert into author (name, gender, country) values ('Elsey Montez', 'F', 'China');
insert into author (name, gender, country) values ('Nappie Dunhill', 'M', 'United States');
insert into author (name, gender, country) values ('Dicky Monnery', 'M', 'Indonesia');
insert into author (name, gender, country) values ('Kris Kroin', 'M', 'Sweden');
insert into author (name, gender, country) values ('Aime Tarbert', 'F', 'East Timor');
insert into author (name, gender, country) values ('Tammie Langton', 'M', 'Samoa');
insert into author (name, gender, country) values ('Lucian Yegoshin', 'M', 'Canada');
insert into author (name, gender, country) values ('Kania Ewells', 'F', 'Albania');
insert into author (name, gender, country) values ('Gayle Hunting', 'M', 'Chile');
insert into author (name, gender, country) values ('Corene Klimov', 'F', 'Kazakhstan');
insert into author (name, gender, country) values ('Lucretia Andries', 'F', 'Brazil');
insert into author (name, gender, country) values ('Gussy Jarrett', 'F', 'China');
insert into author (name, gender, country) values ('Nikolia Jeynes', 'F', 'Brazil');
insert into author (name, gender, country) values ('Ansell Lytton', 'M', 'China');
insert into author (name, gender, country) values ('Pietro Umney', 'M', 'Bulgaria');
insert into author (name, gender, country) values ('Frasco Devenport', 'M', 'South Africa');
insert into author (name, gender, country) values ('Rosemonde Fearnehough', 'F', 'Bangladesh');
insert into author (name, gender, country) values ('Thebault Plitz', 'M', 'Russia');
insert into author (name, gender, country) values ('Welsh Tissiman', 'M', 'Brazil');
insert into author (name, gender, country) values ('Homerus Webber', 'M', 'Bangladesh');
insert into author (name, gender, country) values ('Talbert Finnimore', 'M', 'Spain');
insert into author (name, gender, country) values ('Benyamin Lobell', 'M', 'Philippines');
insert into author (name, gender, country) values ('Dionysus Dunster', 'M', 'France');
insert into author (name, gender, country) values ('Jaimie Gentle', 'F', 'Ethiopia');
insert into author (name, gender, country) values ('Aeriel Speenden', 'F', 'Serbia');
insert into author (name, gender, country) values ('Jena Krishtopaittis', 'F', 'Uruguay');
insert into author (name, gender, country) values ('Ewen Hinze', 'M', 'Belarus');
insert into author (name, gender, country) values ('Ferdinand Ganning', 'M', 'Indonesia');
insert into author (name, gender, country) values ('Charlotta Tytcomb', 'F', 'China');
insert into author (name, gender, country) values ('Ebba Flageul', 'F', 'Poland');
insert into author (name, gender, country) values ('Ardisj Simmance', 'F', 'Peru');
insert into author (name, gender, country) values ('Brien Emptage', 'M', 'Finland');
insert into author (name, gender, country) values ('Vickie Saulter', 'F', 'Latvia');
insert into author (name, gender, country) values ('Weider Rabat', 'M', 'Russia');
insert into author (name, gender, country) values ('Barnabas Bowery', 'M', 'Dominican Republic');
insert into author (name, gender, country) values ('Alidia Treslove', 'F', 'Indonesia');
insert into author (name, gender, country) values ('Nolie Lochrie', 'F', 'South Korea');
insert into author (name, gender, country) values ('Anthe Brayshay', 'F', 'Russia');
insert into author (name, gender, country) values ('Nadiya Schwand', 'F', 'Philippines');
insert into author (name, gender, country) values ('Cinda Witcher', 'F', 'Philippines');
insert into author (name, gender, country) values ('Goddard Priver', 'M', 'Croatia');
insert into author (name, gender, country) values ('Raeann Gamell', 'F', 'Indonesia');
insert into author (name, gender, country) values ('Kimbell Witherbed', 'M', 'Philippines');
insert into author (name, gender, country) values ('Any Ludford', 'M', 'Poland');
insert into author (name, gender, country) values ('Monti McCrackem', 'M', 'China');
insert into author (name, gender, country) values ('Leland Leroux', 'F', 'Portugal');
insert into author (name, gender, country) values ('Alicea Iashvili', 'F', 'Indonesia');
insert into author (name, gender, country) values ('Tabina Churchard', 'F', 'Senegal');
insert into author (name, gender, country) values ('Harli Eslemont', 'F', 'China');
insert into author (name, gender, country) values ('Hamilton Oselton', 'M', 'China');
insert into author (name, gender, country) values ('Donna Gaskell', 'F', 'China');
insert into author (name, gender, country) values ('Gerry Crace', 'M', 'Ukraine');
insert into author (name, gender, country) values ('Rosco Sunderland', 'M', 'Russia');
insert into author (name, gender, country) values ('Mauricio Wynne', 'M', 'France');
insert into author (name, gender, country) values ('Xenia Keysel', 'F', 'China');
insert into author (name, gender, country) values ('Harry Daunter', 'M', 'China');
insert into author (name, gender, country) values ('Trace Curlis', 'M', 'Ivory Coast');
insert into author (name, gender, country) values ('Matthieu MacAlpin', 'M', 'Armenia');
insert into author (name, gender, country) values ('Corty Trusty', 'M', 'China');
insert into author (name, gender, country) values ('Ivar Gullan', 'M', 'France');
insert into author (name, gender, country) values ('Rochella Pirri', 'F', 'France');
insert into author (name, gender, country) values ('Jo-ann Langhorne', 'F', 'Philippines');
insert into author (name, gender, country) values ('Dolley Paule', 'F', 'China');
insert into author (name, gender, country) values ('Hermie Baish', 'M', 'China');
insert into author (name, gender, country) values ('Carry Childes', 'F', 'China');
insert into author (name, gender, country) values ('Darbie Polhill', 'F', 'Denmark');
insert into author (name, gender, country) values ('Meryl Beekmann', 'M', 'Pakistan');
insert into author (name, gender, country) values ('Bea Hunnywell', 'F', 'Mali');
insert into author (name, gender, country) values ('Tamera Killford', 'F', 'Bosnia and Herzegovina');
insert into author (name, gender, country) values ('Sampson Renner', 'M', 'China');
insert into author (name, gender, country) values ('Dot Clack', 'F', 'China');
insert into author (name, gender, country) values ('Steffen Finlay', 'M', 'China');
insert into author (name, gender, country) values ('Letizia Elintune', 'F', 'China');
insert into author (name, gender, country) values ('Ken Vinck', 'M', 'China');
insert into author (name, gender, country) values ('Addi Bogey', 'F', 'Nigeria');
insert into author (name, gender, country) values ('Pennie Putley', 'F', 'Philippines');
insert into author (name, gender, country) values ('Jamil Hitschke', 'M', 'Poland');
insert into author (name, gender, country) values ('Taite Huot', 'M', 'China');
insert into author (name, gender, country) values ('Madel Bendik', 'F', 'Palestinian Territory');
insert into author (name, gender, country) values ('Caroline Caldecot', 'F', 'China');
insert into author (name, gender, country) values ('Maurise Christoffe', 'F', 'China');
insert into author (name, gender, country) values ('Toby Le Barr', 'F', 'Norway');
insert into author (name, gender, country) values ('Berkie Franchioni', 'M', 'China');
insert into author (name, gender, country) values ('Riobard Le Gassick', 'M', 'Czech Republic');
insert into author (name, gender, country) values ('Adina Kenninghan', 'F', 'Pakistan');
insert into author (name, gender, country) values ('Mattheus Tottem', 'M', 'China');
insert into author (name, gender, country) values ('Selena Cuffin', 'F', 'Cameroon');
insert into author (name, gender, country) values ('Bernadene Korda', 'F', 'Mauritius');
insert into author (name, gender, country) values ('Dukie Sarra', 'M', 'China');
insert into author (name, gender, country) values ('Lorettalorna Lefley', 'F', 'Tajikistan');
insert into author (name, gender, country) values ('Susanne Wingham', 'F', 'Peru');
insert into author (name, gender, country) values ('Deena Dunbabin', 'F', 'Philippines');
insert into author (name, gender, country) values ('Tiebout Beadman', 'M', 'Canada');
insert into author (name, gender, country) values ('Tomlin Wrassell', 'M', 'Ecuador');
insert into author (name, gender, country) values ('Stearn Phelipeau', 'M', 'Netherlands');
insert into author (name, gender, country) values ('Ludovico Grahlman', 'M', 'Indonesia');
insert into author (name, gender, country) values ('Lyda Heams', 'F', 'Russia');
insert into author (name, gender, country) values ('Steven Pidgeley', 'M', 'Sweden');
insert into author (name, gender, country) values ('Beverie Tills', 'F', 'Norway');
insert into author (name, gender, country) values ('Rochell Larn', 'F', 'Mexico');
insert into author (name, gender, country) values ('Lay Pattlel', 'M', 'Indonesia');
insert into author (name, gender, country) values ('Hinze Westrey', 'M', 'Macedonia');
insert into author (name, gender, country) values ('Vinnie Daggett', 'F', 'Portugal');
insert into author (name, gender, country) values ('Marcie Cahalan', 'F', 'Poland');
insert into author (name, gender, country) values ('Jemmy Bill', 'F', 'Finland');
insert into author (name, gender, country) values ('Kassia Grube', 'F', 'Netherlands');
insert into author (name, gender, country) values ('Samantha Parrett', 'F', 'Indonesia');
insert into author (name, gender, country) values ('Leodora Hansbury', 'F', 'Poland');
insert into author (name, gender, country) values ('Jojo Gettings', 'F', 'Peru');
insert into author (name, gender, country) values ('Carney Wharin', 'M', 'Indonesia');
insert into author (name, gender, country) values ('Rossy Whitehair', 'M', 'Russia');
insert into author (name, gender, country) values ('Lilllie Redrup', 'F', 'Cape Verde');
insert into author (name, gender, country) values ('Desiree Jindrich', 'F', 'Indonesia');
insert into author (name, gender, country) values ('Cecilio Attwoul', 'M', 'Indonesia');
insert into author (name, gender, country) values ('Hanni Arden', 'F', 'China');
insert into author (name, gender, country) values ('Leopold Pitcaithley', 'M', 'China');
insert into author (name, gender, country) values ('Atalanta Huyche', 'F', 'Croatia');
insert into author (name, gender, country) values ('Kaile Thursfield', 'F', 'China');
insert into author (name, gender, country) values ('Clarey Jellard', 'F', 'Indonesia');
insert into author (name, gender, country) values ('Rurik Jeffries', 'M', 'Qatar');
insert into author (name, gender, country) values ('Moreen Leighton', 'F', 'Netherlands');
insert into author (name, gender, country) values ('Vasilis Idenden', 'M', 'Tunisia');
insert into author (name, gender, country) values ('Bryant Constant', 'M', 'Czech Republic');
insert into author (name, gender, country) values ('Lee Konerding', 'M', 'Mongolia');
insert into author (name, gender, country) values ('Asa Grave', 'M', 'Indonesia');
insert into author (name, gender, country) values ('Justen McCaughen', 'M', 'Indonesia');
insert into author (name, gender, country) values ('Tully Castri', 'M', 'Indonesia');
insert into author (name, gender, country) values ('Jarred Blowfield', 'M', 'Russia');
insert into author (name, gender, country) values ('Eddy Bocking', 'F', 'China');
insert into author (name, gender, country) values ('Berni Lanphier', 'F', 'Russia');
insert into author (name, gender, country) values ('Willamina Krol', 'F', 'Mexico');
insert into author (name, gender, country) values ('Elsey McCritichie', 'F', 'Portugal');
insert into author (name, gender, country) values ('Mercie Urch', 'F', 'China');
insert into author (name, gender, country) values ('Milly Akaster', 'F', 'Brazil');
insert into author (name, gender, country) values ('Derrek Brownhall', 'M', 'Indonesia');
insert into author (name, gender, country) values ('Sven Boatwright', 'M', 'Argentina');
insert into author (name, gender, country) values ('Hirsch Ablott', 'M', 'Canada');
insert into author (name, gender, country) values ('Broderic Lantry', 'M', 'Madagascar');
insert into author (name, gender, country) values ('Judah Brigshaw', 'M', 'Thailand');
insert into author (name, gender, country) values ('Munroe Curado', 'M', 'Canada');
insert into author (name, gender, country) values ('Susana Piggott', 'F', 'Grenada');
insert into author (name, gender, country) values ('Carline Fleisch', 'F', 'Brazil');
insert into author (name, gender, country) values ('Elysha Riggoll', 'F', 'Slovenia');
insert into author (name, gender, country) values ('Orville Mandrey', 'M', 'Venezuela');
insert into author (name, gender, country) values ('Tootsie Presdie', 'F', 'China');
insert into author (name, gender, country) values ('Giovanni Trownson', 'M', 'Poland');
insert into author (name, gender, country) values ('Culley Alexandrescu', 'M', 'Brazil');
insert into author (name, gender, country) values ('Eddi Raeburn', 'F', 'Uzbekistan');
insert into author (name, gender, country) values ('Shea Westraw', 'M', 'Panama');
insert into author (name, gender, country) values ('Creight Harriagn', 'M', 'France');
insert into author (name, gender, country) values ('Brendon Morgan', 'M', 'Norway');
insert into author (name, gender, country) values ('Conn Newvell', 'M', 'Indonesia');
insert into author (name, gender, country) values ('Raquel Euston', 'F', 'Albania');
insert into author (name, gender, country) values ('Jaymie Bettenay', 'M', 'Bosnia and Herzegovina');
insert into author (name, gender, country) values ('Pascale Waleran', 'M', 'China');
insert into author (name, gender, country) values ('Carce Tolmie', 'M', 'United States');
insert into author (name, gender, country) values ('Duky Wishkar', 'M', 'Poland');
insert into author (name, gender, country) values ('Frazer Reen', 'M', 'Mongolia');
insert into author (name, gender, country) values ('Pren Pinkard', 'M', 'France');
insert into author (name, gender, country) values ('Jard Popplestone', 'M', 'Colombia');
insert into author (name, gender, country) values ('Ambros Joint', 'M', 'Honduras');
insert into author (name, gender, country) values ('Bart McIan', 'M', 'Philippines');
insert into author (name, gender, country) values ('Romeo Fautly', 'M', 'China');
insert into author (name, gender, country) values ('Thorsten Fleote', 'M', 'Indonesia');
insert into author (name, gender, country) values ('Lona Beckinsale', 'F', 'France');
insert into author (name, gender, country) values ('Val De Cruce', 'M', 'Philippines');
insert into author (name, gender, country) values ('Constantino Letch', 'M', 'Czech Republic');
insert into author (name, gender, country) values ('Tatiana Wilcox', 'F', 'Sweden');
insert into author (name, gender, country) values ('Ephraim Owain', 'M', 'China');
insert into author (name, gender, country) values ('Maurie Aikman', 'M', 'China');
insert into author (name, gender, country) values ('Dasya Mathiassen', 'F', 'Nepal');
insert into author (name, gender, country) values ('Garold Mobley', 'M', 'Luxembourg');
insert into author (name, gender, country) values ('Elly Roon', 'F', 'Philippines');
insert into author (name, gender, country) values ('Kennedy Fotheringham', 'M', 'Ukraine');
insert into author (name, gender, country) values ('Bern Wimpey', 'M', 'China');
insert into author (name, gender, country) values ('Boote Hyatt', 'M', 'Mexico');
insert into author (name, gender, country) values ('Giuseppe Cornelleau', 'M', 'China');
insert into author (name, gender, country) values ('Yoko Knoles', 'F', 'Serbia');
insert into author (name, gender, country) values ('Rochelle Volke', 'F', 'Ecuador');
insert into author (name, gender, country) values ('Ginger Kob', 'M', 'Somalia');
insert into author (name, gender, country) values ('Penny Aslin', 'M', 'Kazakhstan');
insert into author (name, gender, country) values ('Dionisio Cleator', 'M', 'Albania');
insert into author (name, gender, country) values ('Harp Gopsill', 'M', 'China');
insert into author (name, gender, country) values ('Missy O''Hartigan', 'F', 'Ireland');
insert into author (name, gender, country) values ('Tomaso Oliveira', 'M', 'Malaysia');
insert into author (name, gender, country) values ('Hy Darben', 'M', 'Belarus');
insert into author (name, gender, country) values ('Lorrie Pantlin', 'M', 'Brazil');
insert into author (name, gender, country) values ('Riannon Pendrey', 'F', 'China');
insert into author (name, gender, country) values ('Benji MacGeaney', 'M', 'Ireland');
insert into author (name, gender, country) values ('Masha Miklem', 'F', 'Ukraine');
insert into author (name, gender, country) values ('Tobiah Danaher', 'M', 'China');
insert into author (name, gender, country) values ('Madelon Saintpierre', 'F', 'Poland');
insert into author (name, gender, country) values ('Bjorn Owens', 'M', 'Iran');
insert into author (name, gender, country) values ('Orlando Kemetz', 'M', 'Philippines');
insert into author (name, gender, country) values ('Carine Gilcriest', 'F', 'Indonesia');
insert into author (name, gender, country) values ('Arnold Jarnell', 'M', 'France');
insert into author (name, gender, country) values ('Kassi Mulvy', 'F', 'Indonesia');
insert into author (name, gender, country) values ('Lion Collecott', 'M', 'China');
insert into author (name, gender, country) values ('Lonny Orth', 'M', 'Nigeria');
insert into author (name, gender, country) values ('Odey Conneely', 'M', 'China');
insert into author (name, gender, country) values ('Gayle Etchell', 'F', 'Indonesia');
insert into author (name, gender, country) values ('Mahmoud Bright', 'M', 'Seychelles');
insert into author (name, gender, country) values ('Victoir Weedenburg', 'M', 'United States');
insert into author (name, gender, country) values ('Bruis Ropkes', 'M', 'Dominican Republic');
insert into author (name, gender, country) values ('Moira Hegg', 'F', 'Jordan');
insert into author (name, gender, country) values ('Gertrud Goldhawk', 'F', 'Peru');
insert into author (name, gender, country) values ('Geordie Karlowicz', 'M', 'China');
insert into author (name, gender, country) values ('Etti Loiterton', 'F', 'Peru');
insert into author (name, gender, country) values ('Gweneth Wace', 'F', 'Thailand');
insert into author (name, gender, country) values ('Charlot Allabush', 'F', 'Poland');
insert into author (name, gender, country) values ('Isador Schulter', 'M', 'France');
insert into author (name, gender, country) values ('Redford Bowley', 'M', 'Nigeria');
insert into author (name, gender, country) values ('Pavla Colegate', 'F', 'New Zealand');
insert into author (name, gender, country) values ('Anabella Cuell', 'F', 'Portugal');
insert into author (name, gender, country) values ('Helaina Thurman', 'F', 'American Samoa');
insert into author (name, gender, country) values ('Roosevelt Heber', 'M', 'Portugal');
insert into author (name, gender, country) values ('Francesca Larchier', 'F', 'Philippines');
insert into author (name, gender, country) values ('Natty Yukhov', 'F', 'Slovenia');
insert into author (name, gender, country) values ('Xymenes Craster', 'M', 'Peru');
insert into author (name, gender, country) values ('Ignacio Prevett', 'M', 'China');
insert into author (name, gender, country) values ('Ferris Grimbleby', 'M', 'United States');
insert into author (name, gender, country) values ('Rhys Scollick', 'M', 'Poland');
insert into author (name, gender, country) values ('Jerry Cicculi', 'M', 'Serbia');
insert into author (name, gender, country) values ('Roz Tosh', 'F', 'Philippines');
insert into author (name, gender, country) values ('Gus Budgen', 'M', 'Italy');
insert into author (name, gender, country) values ('Kincaid Gunny', 'M', 'East Timor');
insert into author (name, gender, country) values ('Quinlan McLaughlan', 'M', 'Tonga');
insert into author (name, gender, country) values ('Gae Gronav', 'F', 'American Samoa');
insert into author (name, gender, country) values ('Tymon Cranmere', 'M', 'Ireland');
insert into author (name, gender, country) values ('Abner Patrick', 'M', 'Germany');
insert into author (name, gender, country) values ('Bettina Eatherton', 'F', 'United States');
insert into author (name, gender, country) values ('Eartha Poulson', 'F', 'Algeria');
insert into author (name, gender, country) values ('Scarface Bewsey', 'M', 'Russia');
insert into author (name, gender, country) values ('Tamra Cicchillo', 'F', 'China');
insert into author (name, gender, country) values ('Gunter Shirley', 'M', 'Indonesia');
insert into author (name, gender, country) values ('Alie Bowry', 'F', 'Chile');
insert into author (name, gender, country) values ('Fayette Josifovic', 'F', 'Malaysia');
insert into author (name, gender, country) values ('Jonah Metzke', 'M', 'Japan');
insert into author (name, gender, country) values ('Nessa Kasperski', 'F', 'China');
insert into author (name, gender, country) values ('Monica Vanyukhin', 'F', 'China');
insert into author (name, gender, country) values ('Carling Rosel', 'M', 'Venezuela');
insert into author (name, gender, country) values ('Roselin Pendred', 'F', 'Sweden');
insert into author (name, gender, country) values ('Juanita Agiolfinger', 'F', 'China');
insert into author (name, gender, country) values ('Ravi Whitehurst', 'M', 'China');
insert into author (name, gender, country) values ('Rooney Toffolo', 'M', 'China');
insert into author (name, gender, country) values ('Stacee Hallick', 'M', 'Portugal');
insert into author (name, gender, country) values ('Noby Devon', 'M', 'Cameroon');
insert into author (name, gender, country) values ('Lavena Cardew', 'F', 'China');
insert into author (name, gender, country) values ('Kamilah Gerling', 'F', 'Croatia');
insert into author (name, gender, country) values ('Grayce Guenther', 'F', 'Portugal');
insert into author (name, gender, country) values ('Keefer Garrique', 'M', 'China');
insert into author (name, gender, country) values ('Gabrielle Dauney', 'F', 'Venezuela');
insert into author (name, gender, country) values ('Gunter Kincade', 'M', 'Poland');
insert into author (name, gender, country) values ('Moreen Whiterod', 'F', 'Russia');
insert into author (name, gender, country) values ('Nadiya Fruish', 'F', 'Philippines');
insert into author (name, gender, country) values ('Petrina Dahle', 'F', 'Russia');
insert into author (name, gender, country) values ('Cindra Yetman', 'F', 'Croatia');
insert into author (name, gender, country) values ('Cherianne Barry', 'F', 'Tanzania');
insert into author (name, gender, country) values ('Rica Drysdale', 'F', 'Cyprus');
insert into author (name, gender, country) values ('Benoit Durham', 'M', 'Indonesia');
insert into author (name, gender, country) values ('Rollin McKniely', 'M', 'Tunisia');
insert into author (name, gender, country) values ('Auguste O''Hartnedy', 'F', 'China');
insert into author (name, gender, country) values ('Greta Cremen', 'F', 'China');
insert into author (name, gender, country) values ('Delainey Kleinsmuntz', 'M', 'Japan');
insert into author (name, gender, country) values ('Linea Dowdeswell', 'F', 'Indonesia');
insert into author (name, gender, country) values ('Krishna Haycroft', 'M', 'Spain');
insert into author (name, gender, country) values ('Erina Grigorio', 'F', 'China');
insert into author (name, gender, country) values ('Ulrikaumeko Briton', 'F', 'Portugal');
insert into author (name, gender, country) values ('Orsola Storms', 'F', 'Portugal');
insert into author (name, gender, country) values ('Dru Byrth', 'M', 'Brazil');
insert into author (name, gender, country) values ('Nydia O''Scollain', 'F', 'Sweden');
insert into author (name, gender, country) values ('Leah Staddart', 'F', 'China');
insert into author (name, gender, country) values ('Dallas Clotworthy', 'F', 'Hungary');
insert into author (name, gender, country) values ('Jorgan Lotherington', 'M', 'Russia');
insert into author (name, gender, country) values ('Beau Robertz', 'M', 'Poland');
insert into author (name, gender, country) values ('Alfred Gleadle', 'M', 'Philippines');
insert into author (name, gender, country) values ('Kanya Goldthorp', 'F', 'Finland');
insert into author (name, gender, country) values ('Sapphira Keel', 'F', 'Brazil');
insert into author (name, gender, country) values ('Katharine Goby', 'F', 'Mauritius');
insert into author (name, gender, country) values ('Ilysa Boothe', 'F', 'Philippines');
insert into author (name, gender, country) values ('Madge Wibrow', 'F', 'France');
insert into author (name, gender, country) values ('Timothee Huws', 'M', 'China');
insert into author (name, gender, country) values ('Marion Moreman', 'M', 'Czech Republic');
insert into author (name, gender, country) values ('Karolina Brosi', 'F', 'Poland');
insert into author (name, gender, country) values ('Cory Brayshay', 'F', 'China');
insert into author (name, gender, country) values ('Rita O''Keenan', 'F', 'France');
insert into author (name, gender, country) values ('Rose Smogur', 'F', 'China');
insert into author (name, gender, country) values ('Marje Quidenham', 'F', 'China');
insert into author (name, gender, country) values ('Finn Golthorpp', 'M', 'Honduras');
insert into author (name, gender, country) values ('Bradly Hounsom', 'M', 'Sweden');
insert into author (name, gender, country) values ('Amandi Rodenburg', 'F', 'Morocco');
insert into author (name, gender, country) values ('Trumaine Reder', 'M', 'Niger');
insert into author (name, gender, country) values ('Davin Steade', 'M', 'China');
insert into author (name, gender, country) values ('Abdel Solan', 'M', 'Russia');
insert into author (name, gender, country) values ('Kristo Cartwright', 'M', 'Vietnam');
insert into author (name, gender, country) values ('Richmound Joret', 'M', 'United States');
insert into author (name, gender, country) values ('Janka Cushelly', 'F', 'Belarus');
insert into author (name, gender, country) values ('Babs Duguid', 'F', 'Thailand');
insert into author (name, gender, country) values ('Tremaine McAtamney', 'M', 'Seychelles');
insert into author (name, gender, country) values ('Patrizia Neachell', 'F', 'United States');
insert into author (name, gender, country) values ('Ario Asquez', 'M', 'Thailand');
insert into author (name, gender, country) values ('Isobel Carr', 'F', 'Sweden');
insert into author (name, gender, country) values ('Shaine Gillibrand', 'F', 'Brazil');
insert into author (name, gender, country) values ('Eustacia Blayney', 'F', 'Indonesia');
insert into author (name, gender, country) values ('Gisele Bretherick', 'F', 'Sweden');
insert into author (name, gender, country) values ('Cherrita Helm', 'F', 'United States');
insert into author (name, gender, country) values ('Erwin Middlemist', 'M', 'China');
insert into author (name, gender, country) values ('Jervis Maunsell', 'M', 'Poland');
insert into author (name, gender, country) values ('Lindsay Edelheid', 'F', 'Norway');
insert into author (name, gender, country) values ('Linoel Johnys', 'M', 'Sweden');
insert into author (name, gender, country) values ('Diego Dransfield', 'M', 'Indonesia');
insert into author (name, gender, country) values ('Cassius Savil', 'M', 'Vietnam');
insert into author (name, gender, country) values ('Blakeley Vondracek', 'F', 'Greece');
insert into author (name, gender, country) values ('Barn Lodewick', 'M', 'Czech Republic');
insert into author (name, gender, country) values ('Jordon Allbones', 'M', 'Russia');
insert into author (name, gender, country) values ('Jody Paprotny', 'F', 'Ukraine');
insert into author (name, gender, country) values ('Ree Peirson', 'F', 'Kazakhstan');
insert into author (name, gender, country) values ('Avigdor Obert', 'M', 'Philippines');
insert into author (name, gender, country) values ('Alvinia Symcox', 'F', 'Indonesia');
insert into author (name, gender, country) values ('Marketa Saleway', 'F', 'China');
insert into author (name, gender, country) values ('Mia Priter', 'F', 'Sri Lanka');
insert into author (name, gender, country) values ('Wilfred Mitchelhill', 'M', 'Greece');
insert into author (name, gender, country) values ('Benoite Paddemore', 'F', 'Cocos Islands');
insert into author (name, gender, country) values ('Kimbell Cammacke', 'M', 'Poland');
insert into author (name, gender, country) values ('Helene Goncalo', 'F', 'Ukraine');
insert into author (name, gender, country) values ('Locke Caghan', 'M', 'Poland');
insert into author (name, gender, country) values ('Giff Bridges', 'M', 'Brazil');
insert into author (name, gender, country) values ('Ludvig Mougeot', 'M', 'Indonesia');
insert into author (name, gender, country) values ('Rasia Castaneda', 'F', 'China');
insert into author (name, gender, country) values ('Tripp Shergold', 'M', 'Sweden');
insert into author (name, gender, country) values ('Imogene Vannoort', 'F', 'Macedonia');
insert into author (name, gender, country) values ('Zorine McAw', 'F', 'Colombia');
insert into author (name, gender, country) values ('Brinna Pernell', 'F', 'Sweden');
insert into author (name, gender, country) values ('Mariejeanne Atte-Stone', 'F', 'Philippines');
insert into author (name, gender, country) values ('Cheston Cadney', 'M', 'Czech Republic');
insert into author (name, gender, country) values ('Galen Chappelle', 'M', 'Peru');
insert into author (name, gender, country) values ('Kai Etchingham', 'F', 'Cuba');
insert into author (name, gender, country) values ('Layla Crickmore', 'F', 'China');
insert into author (name, gender, country) values ('Ted Foulcher', 'M', 'Brazil');
insert into author (name, gender, country) values ('Anne Sneden', 'F', 'Poland');
insert into author (name, gender, country) values ('Tore Pauluzzi', 'M', 'Sweden');
insert into author (name, gender, country) values ('Burr Jendricke', 'M', 'China');
insert into author (name, gender, country) values ('Fee Puttergill', 'M', 'Japan');
insert into author (name, gender, country) values ('Cassy Asher', 'F', 'Russia');
insert into author (name, gender, country) values ('Thane Cotty', 'M', 'Indonesia');
insert into author (name, gender, country) values ('Daisie Malkin', 'F', 'Vietnam');
insert into author (name, gender, country) values ('Eadmund Kochs', 'M', 'Saudi Arabia');
insert into author (name, gender, country) values ('Roderick Plumer', 'M', 'Russia');
insert into author (name, gender, country) values ('Elmer Ianitti', 'M', 'Brazil');
insert into author (name, gender, country) values ('Clement Clerk', 'M', 'Iraq');
insert into author (name, gender, country) values ('Farleigh Englefield', 'M', 'Japan');
insert into author (name, gender, country) values ('Jeremias Gwinnett', 'M', 'China');
insert into author (name, gender, country) values ('Even Nand', 'M', 'Indonesia');
insert into author (name, gender, country) values ('Schuyler Haddow', 'M', 'China');
insert into author (name, gender, country) values ('Marys Till', 'F', 'Spain');
insert into author (name, gender, country) values ('Vivianne Shakle', 'F', 'Spain');
insert into author (name, gender, country) values ('Enriqueta Murton', 'F', 'China');
insert into author (name, gender, country) values ('Jayson O'' Driscoll', 'M', 'China');
insert into author (name, gender, country) values ('Carroll Coultous', 'F', 'Kazakhstan');
insert into author (name, gender, country) values ('Kalila Whitfeld', 'F', 'Poland');
insert into author (name, gender, country) values ('Patrick Hackworth', 'M', 'Macedonia');
insert into author (name, gender, country) values ('Nicolas Grzesiak', 'M', 'Finland');
insert into author (name, gender, country) values ('Berke Cobbald', 'M', 'Philippines');
insert into author (name, gender, country) values ('Wakefield Brotherick', 'M', 'China');
insert into author (name, gender, country) values ('Saraann Palffy', 'F', 'Portugal');
insert into author (name, gender, country) values ('Enrique Bruin', 'M', 'Guatemala');
insert into author (name, gender, country) values ('Junette Labusch', 'F', 'Canada');
insert into author (name, gender, country) values ('Rancell Bicker', 'M', 'Nigeria');
insert into author (name, gender, country) values ('Devin Pimlock', 'F', 'Czech Republic');
insert into author (name, gender, country) values ('Monika De Vries', 'F', 'Malaysia');
insert into author (name, gender, country) values ('Harcourt Marwick', 'M', 'Peru');
insert into author (name, gender, country) values ('Gates Deaton', 'F', 'Russia');
insert into author (name, gender, country) values ('Chadd Goutcher', 'M', 'China');
insert into author (name, gender, country) values ('Llewellyn Gai', 'M', 'Philippines');
insert into author (name, gender, country) values ('Drud Houlridge', 'M', 'Philippines');
insert into author (name, gender, country) values ('Godfry Rowledge', 'M', 'China');
insert into author (name, gender, country) values ('Dalis Fantini', 'M', 'Russia');
insert into author (name, gender, country) values ('Giralda Blackden', 'F', 'China');
insert into author (name, gender, country) values ('Olivier Thayre', 'M', 'Philippines');
insert into author (name, gender, country) values ('Annabel Tesimon', 'F', 'El Salvador');
insert into author (name, gender, country) values ('Fowler Gye', 'M', 'China');
insert into author (name, gender, country) values ('Camila McNeely', 'F', 'France');
insert into author (name, gender, country) values ('Patty Beiderbeck', 'M', 'China');
insert into author (name, gender, country) values ('Sheri Pakeman', 'F', 'Chile');
insert into author (name, gender, country) values ('Oralie Pendrid', 'F', 'France');
insert into author (name, gender, country) values ('Boote Kedwell', 'M', 'Russia');
insert into author (name, gender, country) values ('Humberto Caizley', 'M', 'Saudi Arabia');
insert into author (name, gender, country) values ('Lucienne McGrayle', 'F', 'Russia');
insert into author (name, gender, country) values ('Rick Denziloe', 'M', 'Thailand');
insert into author (name, gender, country) values ('Carey Lockyer', 'F', 'Peru');
insert into author (name, gender, country) values ('Granger Tomaini', 'M', 'China');
insert into author (name, gender, country) values ('Andres Farrans', 'M', 'Egypt');
insert into author (name, gender, country) values ('Ned Radnage', 'M', 'Russia');
insert into author (name, gender, country) values ('Lyndsey Fellows', 'F', 'Poland');
insert into author (name, gender, country) values ('Travus Simonitto', 'M', 'Philippines');
insert into author (name, gender, country) values ('Avery Margetson', 'M', 'Philippines');
insert into author (name, gender, country) values ('Gunilla Liccardi', 'F', 'Thailand');
insert into author (name, gender, country) values ('Cammy Faull', 'M', 'China');
insert into author (name, gender, country) values ('Maxwell Sheen', 'M', 'Hong Kong');
insert into author (name, gender, country) values ('Emile Randall', 'M', 'Indonesia');
insert into author (name, gender, country) values ('Guglielmo Fermer', 'M', 'Greece');
insert into author (name, gender, country) values ('Theresita Willmer', 'F', 'Russia');
insert into author (name, gender, country) values ('Laird Hartwright', 'M', 'Croatia');
insert into author (name, gender, country) values ('Mohandis Cowpertwait', 'M', 'France');
insert into author (name, gender, country) values ('Federico Seawright', 'M', 'Panama');
insert into author (name, gender, country) values ('Aime Piolli', 'F', 'Japan');
insert into author (name, gender, country) values ('Adolph Lies', 'M', 'Brazil');
insert into author (name, gender, country) values ('Douglas Comberbach', 'M', 'Brazil');
insert into author (name, gender, country) values ('Cesaro Kryszkiecicz', 'M', 'Colombia');
insert into author (name, gender, country) values ('Chloette Mawd', 'F', 'Australia');
insert into author (name, gender, country) values ('Karly Lovel', 'F', 'Central African Republic');
insert into author (name, gender, country) values ('Parrnell Tookill', 'M', 'China');
insert into author (name, gender, country) values ('Sybila Woodyeare', 'F', 'Russia');
insert into author (name, gender, country) values ('Merlina Chataignier', 'F', 'Russia');
insert into author (name, gender, country) values ('Erhart Dun', 'M', 'Ukraine');
insert into author (name, gender, country) values ('Rosabella Georgius', 'F', 'Japan');
insert into author (name, gender, country) values ('Waylan Canto', 'M', 'Tajikistan');
insert into author (name, gender, country) values ('Gillie Serjeantson', 'F', 'Russia');
insert into author (name, gender, country) values ('Lorinda Shearman', 'F', 'Philippines');
insert into author (name, gender, country) values ('Lyssa Absolem', 'F', 'Portugal');
insert into author (name, gender, country) values ('Lyndsay Griffitts', 'F', 'Iran');
insert into author (name, gender, country) values ('Maurizio Fenner', 'M', 'Brazil');
insert into author (name, gender, country) values ('Koressa Blanpein', 'F', 'Russia');
insert into author (name, gender, country) values ('Nertie Orteaux', 'F', 'Czech Republic');
insert into author (name, gender, country) values ('Tremaine Pavlov', 'M', 'Colombia');
insert into author (name, gender, country) values ('Iggy Banthorpe', 'M', 'Philippines');
insert into author (name, gender, country) values ('Abbye Mourbey', 'F', 'Swaziland');
insert into author (name, gender, country) values ('Wenonah Di Angelo', 'F', 'China');
insert into author (name, gender, country) values ('Johan Lortzing', 'M', 'Sweden');
insert into author (name, gender, country) values ('Trescha Thoresbie', 'F', 'Argentina');
insert into author (name, gender, country) values ('Bert Nockells', 'F', 'Mongolia');
insert into author (name, gender, country) values ('Harrie Keslake', 'F', 'China');
insert into author (name, gender, country) values ('Chan Shale', 'M', 'China');
insert into author (name, gender, country) values ('Gran Itzkovwitch', 'M', 'Yemen');
insert into author (name, gender, country) values ('Norbie Tireman', 'M', 'Yemen');
insert into author (name, gender, country) values ('Goran Sloane', 'M', 'Kenya');
insert into author (name, gender, country) values ('Patsy Caston', 'F', 'Portugal');
insert into author (name, gender, country) values ('Manfred Dulanty', 'M', 'China');
insert into author (name, gender, country) values ('Sheree Haxbie', 'F', 'China');
insert into author (name, gender, country) values ('Monty Pankethman', 'M', 'Sweden');
insert into author (name, gender, country) values ('Karoly Clarabut', 'F', 'Tanzania');
insert into author (name, gender, country) values ('Brina Timpany', 'F', 'Venezuela');
insert into author (name, gender, country) values ('Mariam Tooze', 'F', 'Tanzania');
insert into author (name, gender, country) values ('Fletcher Whorlton', 'M', 'Czech Republic');
insert into author (name, gender, country) values ('Jillie Sharpless', 'F', 'Madagascar');
insert into author (name, gender, country) values ('Estell Lindholm', 'F', 'China');
insert into author (name, gender, country) values ('Shell Ronchi', 'M', 'Malta');
insert into author (name, gender, country) values ('Humfried Yarn', 'M', 'Russia');
insert into author (name, gender, country) values ('Alvis Fillgate', 'M', 'Zambia');
insert into author (name, gender, country) values ('Rab Freeth', 'M', 'China');
insert into author (name, gender, country) values ('Davin Hellmer', 'M', 'Sweden');
insert into author (name, gender, country) values ('Datha Skatcher', 'F', 'China');
insert into author (name, gender, country) values ('Verney Bader', 'M', 'Philippines');
insert into author (name, gender, country) values ('Corinne Dominguez', 'F', 'China');
insert into author (name, gender, country) values ('Rodolphe Jacquemy', 'M', 'Cameroon');
insert into author (name, gender, country) values ('Vannie Drohane', 'F', 'Peru');
insert into author (name, gender, country) values ('Yehudit Maxsted', 'M', 'China');
insert into author (name, gender, country) values ('Jameson Katte', 'M', 'Portugal');
insert into author (name, gender, country) values ('Alissa Tincey', 'F', 'China');
insert into author (name, gender, country) values ('Myrvyn Elnough', 'M', 'Poland');
insert into author (name, gender, country) values ('Salvidor Clashe', 'M', 'Indonesia');
insert into author (name, gender, country) values ('Genny Romayne', 'F', 'Lithuania');
insert into author (name, gender, country) values ('Delbert Upshall', 'M', 'Egypt');
insert into author (name, gender, country) values ('Standford Coard', 'M', 'Albania');
insert into author (name, gender, country) values ('Timothy Piesold', 'M', 'Ireland');
insert into author (name, gender, country) values ('Myra Mimmack', 'F', 'Ireland');
insert into author (name, gender, country) values ('Minda Gouly', 'F', 'Bahamas');
insert into author (name, gender, country) values ('Catlee Fernan', 'F', 'Malaysia');
insert into author (name, gender, country) values ('Taylor Cole', 'M', 'Nigeria');
insert into author (name, gender, country) values ('Shaun Vernazza', 'F', 'Cuba');
insert into author (name, gender, country) values ('Oliy Wastling', 'F', 'China');
insert into author (name, gender, country) values ('Roseanna Klimt', 'F', 'Pakistan');
insert into author (name, gender, country) values ('Heinrick Greensall', 'M', 'China');
insert into author (name, gender, country) values ('Reinhard Maryman', 'M', 'Guatemala');
insert into author (name, gender, country) values ('Jehanna Pardie', 'F', 'Vietnam');
insert into author (name, gender, country) values ('Burty Rawlin', 'M', 'Poland');
insert into author (name, gender, country) values ('Doug Staveley', 'M', 'Brazil');
insert into author (name, gender, country) values ('Leonard Tomaini', 'M', 'Kazakhstan');
insert into author (name, gender, country) values ('Jeremy Buckel', 'M', 'Nigeria');
insert into author (name, gender, country) values ('Mildrid Chattoe', 'F', 'Sweden');
insert into author (name, gender, country) values ('Nickolai Pettitt', 'M', 'Peru');
insert into author (name, gender, country) values ('Mella Kerins', 'F', 'Iran');
insert into author (name, gender, country) values ('Antonina Seilmann', 'F', 'China');
insert into author (name, gender, country) values ('Veradis Midgely', 'F', 'Russia');
insert into author (name, gender, country) values ('Catha Van Der Straaten', 'F', 'Indonesia');
insert into author (name, gender, country) values ('Morna Van den Hof', 'F', 'Belarus');
insert into author (name, gender, country) values ('Penn Sandercock', 'M', 'Norway');
insert into author (name, gender, country) values ('Gay Urwin', 'M', 'Canada');
insert into author (name, gender, country) values ('Beau Treherne', 'M', 'Colombia');
insert into author (name, gender, country) values ('Caye Crombie', 'F', 'Brazil');
insert into author (name, gender, country) values ('Eleanore Hansberry', 'F', 'Poland');
insert into author (name, gender, country) values ('Pip Yendle', 'M', 'Philippines');
insert into author (name, gender, country) values ('Merline Fernandes', 'F', 'Mauritius');
insert into author (name, gender, country) values ('Sonnie Wyman', 'F', 'Zimbabwe');
insert into author (name, gender, country) values ('Rockwell Quoit', 'M', 'Pakistan');
insert into author (name, gender, country) values ('Cal Skellion', 'M', 'China');
insert into author (name, gender, country) values ('Curtice McVitty', 'M', 'Israel');
insert into author (name, gender, country) values ('Hephzibah Briggs', 'F', 'Philippines');
insert into author (name, gender, country) values ('Sherman Burnie', 'M', 'Russia');
insert into author (name, gender, country) values ('Stanford Seint', 'M', 'Brazil');
insert into author (name, gender, country) values ('Barbra Martygin', 'F', 'Portugal');
insert into author (name, gender, country) values ('Eduard Yeomans', 'M', 'Brazil');
insert into author (name, gender, country) values ('Rourke Hassard', 'M', 'Czech Republic');
insert into author (name, gender, country) values ('Erny Moffatt', 'M', 'Peru');
insert into author (name, gender, country) values ('Fionna Geertsen', 'F', 'China');
insert into author (name, gender, country) values ('Raymond Noke', 'M', 'China');
insert into author (name, gender, country) values ('Aime Daveley', 'F', 'Indonesia');
insert into author (name, gender, country) values ('Poul Simcoe', 'M', 'Indonesia');
insert into author (name, gender, country) values ('Augustina Pennells', 'F', 'Chile');
insert into author (name, gender, country) values ('Keelia Woofinden', 'F', 'China');
insert into author (name, gender, country) values ('Bree Feaviour', 'F', 'Portugal');
insert into author (name, gender, country) values ('Allissa Burnand', 'F', 'Indonesia');
insert into author (name, gender, country) values ('Beaufort Matthiae', 'M', 'Russia');
insert into author (name, gender, country) values ('Bradly Kennler', 'M', 'Russia');
insert into author (name, gender, country) values ('Sherm Barensen', 'M', 'France');
insert into author (name, gender, country) values ('Pennie Hellikes', 'M', 'Poland');
insert into author (name, gender, country) values ('Devora Bollum', 'F', 'Colombia');
insert into author (name, gender, country) values ('Randi Allward', 'F', 'Sweden');
insert into author (name, gender, country) values ('Nil Pikesley', 'M', 'Indonesia');
insert into author (name, gender, country) values ('Darci Deelay', 'F', 'Czech Republic');
insert into author (name, gender, country) values ('Boothe Janata', 'M', 'Indonesia');
insert into author (name, gender, country) values ('Gennie Ramsdell', 'F', 'Serbia');
insert into author (name, gender, country) values ('Burke Magson', 'M', 'Poland');
insert into author (name, gender, country) values ('Kathy Rawle', 'F', 'China');
insert into author (name, gender, country) values ('Reece Seaborn', 'M', 'Indonesia');
insert into author (name, gender, country) values ('Allegra Beet', 'F', 'Uganda');
insert into author (name, gender, country) values ('Matti Gibke', 'F', 'China');
insert into author (name, gender, country) values ('Gilbertina Climson', 'F', 'Taiwan');
insert into author (name, gender, country) values ('Cory Mc Trusty', 'M', 'China');
insert into author (name, gender, country) values ('Zelda Dallyn', 'F', 'Philippines');
insert into author (name, gender, country) values ('Shellie Rouch', 'F', 'New Caledonia');
insert into author (name, gender, country) values ('Clayborne Mcmanaman', 'M', 'Japan');
insert into author (name, gender, country) values ('Phedra Volke', 'F', 'Brazil');
insert into author (name, gender, country) values ('Alida Sandwick', 'F', 'Turkey');
insert into author (name, gender, country) values ('Melina Hubberstey', 'F', 'El Salvador');
insert into author (name, gender, country) values ('Etienne MacMaykin', 'M', 'China');
insert into author (name, gender, country) values ('Laurice Ambrozewicz', 'F', 'China');
insert into author (name, gender, country) values ('Kristina Niles', 'F', 'Poland');
insert into author (name, gender, country) values ('Siobhan Hurrion', 'F', 'Bermuda');
insert into author (name, gender, country) values ('Dare Rennie', 'M', 'Philippines');
insert into author (name, gender, country) values ('Anthony Bilson', 'M', 'Philippines');
insert into author (name, gender, country) values ('Parsifal Winsor', 'M', 'Brazil');
insert into author (name, gender, country) values ('Jereme Ditchett', 'M', 'Nigeria');
insert into author (name, gender, country) values ('Gawain Garretson', 'M', 'Portugal');
insert into author (name, gender, country) values ('Hadrian Munton', 'M', 'Indonesia');
insert into author (name, gender, country) values ('Sigismund Rothery', 'M', 'Belarus');
insert into author (name, gender, country) values ('Mendie Halsho', 'M', 'United States');
insert into author (name, gender, country) values ('Allianora Denziloe', 'F', 'Argentina');
insert into author (name, gender, country) values ('Reyna Cape', 'F', 'New Zealand');
insert into author (name, gender, country) values ('Camilla Conaghy', 'F', 'China');
insert into author (name, gender, country) values ('Erie Vigus', 'M', 'China');
insert into author (name, gender, country) values ('Morlee Burchard', 'M', 'China');
insert into author (name, gender, country) values ('Jerrie McGuire', 'M', 'Micronesia');
insert into author (name, gender, country) values ('Kevina Golby', 'F', 'Mexico');
insert into author (name, gender, country) values ('Clarence Trevna', 'M', 'Brazil');
insert into author (name, gender, country) values ('Guthry Boud', 'M', 'Indonesia');
insert into author (name, gender, country) values ('Mart Kelner', 'M', 'Philippines');
insert into author (name, gender, country) values ('Tybi Roakes', 'F', 'France');
insert into author (name, gender, country) values ('Moshe Fayerbrother', 'M', 'Finland');
insert into author (name, gender, country) values ('Nikkie Cooper', 'F', 'Japan');
insert into author (name, gender, country) values ('Uriah Cawood', 'M', 'Hong Kong');
insert into author (name, gender, country) values ('Kath Parradye', 'F', 'Democratic Republic of the Congo');
insert into author (name, gender, country) values ('Christie Brister', 'F', 'Gambia');
insert into author (name, gender, country) values ('Ameline Toward', 'F', 'Portugal');
insert into author (name, gender, country) values ('Arlena M''Barron', 'F', 'Colombia');
insert into author (name, gender, country) values ('Guillemette Seak', 'F', 'Ireland');
insert into author (name, gender, country) values ('Alfie Ferrulli', 'F', 'China');
insert into author (name, gender, country) values ('Bernadette Ferenc', 'F', 'Colombia');
insert into author (name, gender, country) values ('Yorker Patriskson', 'M', 'Ukraine');
insert into author (name, gender, country) values ('Scotti Demann', 'M', 'United States');
insert into author (name, gender, country) values ('Oralia Uebel', 'F', 'Colombia');
insert into author (name, gender, country) values ('Winslow MacLeod', 'M', 'China');
insert into author (name, gender, country) values ('Delmer Demeza', 'M', 'Croatia');
insert into author (name, gender, country) values ('Tressa Barrell', 'F', 'China');
insert into author (name, gender, country) values ('Stacie Kyttor', 'F', 'Canada');
insert into author (name, gender, country) values ('Joann Dutnall', 'F', 'United States');
insert into author (name, gender, country) values ('Aurthur Cleaves', 'M', 'Brazil');
insert into author (name, gender, country) values ('Lezley Northen', 'M', 'Germany');
insert into author (name, gender, country) values ('Talia Jeromson', 'F', 'China');
insert into author (name, gender, country) values ('Lamont Bordis', 'M', 'Brazil');
insert into author (name, gender, country) values ('Smith Lavarack', 'M', 'Russia');
insert into author (name, gender, country) values ('Marylee Oleksinski', 'F', 'Finland');
insert into author (name, gender, country) values ('Marsh Acarson', 'M', 'Russia');
insert into author (name, gender, country) values ('Cora Elcombe', 'F', 'South Africa');
insert into author (name, gender, country) values ('Rheta McQuaker', 'F', 'France');
insert into author (name, gender, country) values ('Micheil Tweedle', 'M', 'Poland');
insert into author (name, gender, country) values ('Caleb Gittus', 'M', 'Indonesia');
insert into author (name, gender, country) values ('Art Davydzenko', 'M', 'Russia');
insert into author (name, gender, country) values ('Katherina Schelle', 'F', 'Poland');
insert into author (name, gender, country) values ('Tanhya Jeanet', 'F', 'Russia');
insert into author (name, gender, country) values ('Merell Ghiraldi', 'M', 'Ireland');
insert into author (name, gender, country) values ('Rowe Strippel', 'F', 'China');
insert into author (name, gender, country) values ('Melly Waterman', 'F', 'China');
insert into author (name, gender, country) values ('Lidia Goldstraw', 'F', 'Iran');
insert into author (name, gender, country) values ('Cory O''Driscoll', 'M', 'China');
insert into author (name, gender, country) values ('Veriee Cowap', 'F', 'Comoros');
insert into author (name, gender, country) values ('Kristin Jeff', 'F', 'Ethiopia');
insert into author (name, gender, country) values ('Emmie Shorto', 'F', 'Serbia');
insert into author (name, gender, country) values ('Shari O''Concannon', 'F', 'Argentina');
insert into author (name, gender, country) values ('Langsdon Luce', 'M', 'Zimbabwe');
insert into author (name, gender, country) values ('Bethena Mundell', 'F', 'Canada');
insert into author (name, gender, country) values ('Carmen Keel', 'F', 'China');
insert into author (name, gender, country) values ('Hertha Hulett', 'F', 'Serbia');
insert into author (name, gender, country) values ('Ludovico Worcester', 'M', 'United States');
insert into author (name, gender, country) values ('Nina McGilleghole', 'F', 'Russia');
insert into author (name, gender, country) values ('Aline Penticoot', 'F', 'Azerbaijan');
insert into author (name, gender, country) values ('Halsey Earngy', 'M', 'Japan');
insert into author (name, gender, country) values ('Elberta Gors', 'F', 'Serbia');
insert into author (name, gender, country) values ('Nicholle Small', 'F', 'China');
insert into author (name, gender, country) values ('Trevor Arrol', 'M', 'Indonesia');
insert into author (name, gender, country) values ('Devon Groome', 'F', 'Thailand');
insert into author (name, gender, country) values ('Anne Yoskowitz', 'F', 'China');
insert into author (name, gender, country) values ('Titus Ranken', 'M', 'United States');
insert into author (name, gender, country) values ('Torr Witherden', 'M', 'Portugal');
insert into author (name, gender, country) values ('Trueman Salvatore', 'M', 'China');
insert into author (name, gender, country) values ('Gabe Hagston', 'M', 'North Korea');
insert into author (name, gender, country) values ('Niels Knolles-Green', 'M', 'Philippines');
insert into author (name, gender, country) values ('Letitia Zupo', 'F', 'United States');
insert into author (name, gender, country) values ('Luce Gresser', 'M', 'Thailand');
insert into author (name, gender, country) values ('Keely MacCaffrey', 'F', 'China');
insert into author (name, gender, country) values ('Tallia Bason', 'F', 'France');
insert into author (name, gender, country) values ('Rollins Whardley', 'M', 'United Kingdom');
insert into author (name, gender, country) values ('April Rotherforth', 'F', 'Czech Republic');
insert into author (name, gender, country) values ('Mendel Shere', 'M', 'Indonesia');
insert into author (name, gender, country) values ('Sarene Gordon', 'F', 'China');
insert into author (name, gender, country) values ('Cello Vannozzii', 'M', 'China');
insert into author (name, gender, country) values ('Jules Haibel', 'M', 'Croatia');
insert into author (name, gender, country) values ('Vick Minchinden', 'M', 'Czech Republic');
insert into author (name, gender, country) values ('Kristan Temprell', 'F', 'Zambia');
insert into author (name, gender, country) values ('Ugo Ayrton', 'M', 'Azerbaijan');
insert into author (name, gender, country) values ('Ranna Castiglione', 'F', 'China');
insert into author (name, gender, country) values ('Sondra Hayth', 'F', 'Philippines');
insert into author (name, gender, country) values ('Kanya Lorans', 'F', 'Indonesia');
insert into author (name, gender, country) values ('Lettie Rosen', 'F', 'Poland');
insert into author (name, gender, country) values ('Halimeda Manderson', 'F', 'Jordan');
insert into author (name, gender, country) values ('Luca Durdle', 'M', 'Peru');
insert into author (name, gender, country) values ('Orren Danett', 'M', 'Ukraine');
insert into author (name, gender, country) values ('Michael Tuxsell', 'M', 'Vietnam');
insert into author (name, gender, country) values ('Alic Hubane', 'M', 'Poland');
insert into author (name, gender, country) values ('Dareen Joselin', 'F', 'China');
insert into author (name, gender, country) values ('Farra Corbridge', 'F', 'China');
insert into author (name, gender, country) values ('Cloris Carradice', 'F', 'China');
insert into author (name, gender, country) values ('Sarina Dymott', 'F', 'Portugal');
insert into author (name, gender, country) values ('Eddi McLaine', 'F', 'Indonesia');
insert into author (name, gender, country) values ('Damien Abrahamson', 'M', 'China');
insert into author (name, gender, country) values ('Raphaela Sayes', 'F', 'Indonesia');
insert into author (name, gender, country) values ('Pascale Binge', 'M', 'France');
insert into author (name, gender, country) values ('Marcelo Kilbey', 'M', 'China');
insert into author (name, gender, country) values ('Wallache Oldmeadow', 'M', 'Latvia');
insert into author (name, gender, country) values ('Gilberto Alldis', 'M', 'Ukraine');
insert into author (name, gender, country) values ('Wallie Atlay', 'M', 'United States');
insert into author (name, gender, country) values ('Lem Hartgill', 'M', 'Poland');
insert into author (name, gender, country) values ('Si Tomasello', 'M', 'Thailand');
insert into author (name, gender, country) values ('Pavla Bedinn', 'F', 'Russia');
insert into author (name, gender, country) values ('Sinclair Drain', 'M', 'Mexico');
insert into author (name, gender, country) values ('Abeu Braunston', 'M', 'Bosnia and Herzegovina');
insert into author (name, gender, country) values ('Ruddy Mosby', 'M', 'China');
insert into author (name, gender, country) values ('Marne Castagnier', 'F', 'Indonesia');
insert into author (name, gender, country) values ('Zia Leather', 'F', 'Guinea');
insert into author (name, gender, country) values ('Scarlet Roebottom', 'F', 'Indonesia');
insert into author (name, gender, country) values ('Darline Schukert', 'F', 'Ukraine');
insert into author (name, gender, country) values ('Sula Pinckard', 'F', 'Azerbaijan');
insert into author (name, gender, country) values ('Hollis Cruickshank', 'M', 'Poland');
insert into author (name, gender, country) values ('Westbrook Norton', 'M', 'Poland');
insert into author (name, gender, country) values ('Haley Cornilli', 'M', 'Brazil');
insert into author (name, gender, country) values ('Edmund Pratton', 'M', 'Japan');
insert into author (name, gender, country) values ('Bernelle Fox', 'F', 'Vietnam');
insert into author (name, gender, country) values ('Ricky Mildenhall', 'F', 'China');
insert into author (name, gender, country) values ('Rita Powell', 'F', 'Sweden');
insert into author (name, gender, country) values ('Angie Owers', 'F', 'Mexico');
insert into author (name, gender, country) values ('Helenka King', 'F', 'Indonesia');
insert into author (name, gender, country) values ('Ludovika Nutley', 'F', 'Sweden');
insert into author (name, gender, country) values ('Glenden Deniskevich', 'M', 'Malta');
insert into author (name, gender, country) values ('Batholomew Larkings', 'M', 'China');
insert into author (name, gender, country) values ('Sanderson Garken', 'M', 'Palestinian Territory');
insert into author (name, gender, country) values ('Vale Jephcote', 'F', 'Indonesia');
insert into author (name, gender, country) values ('Bobbie Welman', 'M', 'Bolivia');
insert into author (name, gender, country) values ('Enoch Laherty', 'M', 'Guatemala');
insert into author (name, gender, country) values ('Paten McCuis', 'M', 'Greece');
insert into author (name, gender, country) values ('Rasia Jessen', 'F', 'Sweden');
insert into author (name, gender, country) values ('Peggy Sandercock', 'F', 'Indonesia');
insert into author (name, gender, country) values ('Leonanie Penhaleurack', 'F', 'Philippines');
insert into author (name, gender, country) values ('Reinwald Hartus', 'M', 'Philippines');
insert into author (name, gender, country) values ('Maison Stealey', 'M', 'Indonesia');
insert into author (name, gender, country) values ('Carissa Norres', 'F', 'Morocco');
insert into author (name, gender, country) values ('Zane Nesfield', 'M', 'Slovenia');
insert into author (name, gender, country) values ('Phillip Kellitt', 'M', 'China');
insert into author (name, gender, country) values ('Russ Parlet', 'M', 'China');
insert into author (name, gender, country) values ('Devin Millson', 'F', 'Malaysia');
insert into author (name, gender, country) values ('Sharai Maplethorp', 'F', 'Peru');
insert into author (name, gender, country) values ('Bellanca Upjohn', 'F', 'Ukraine');
insert into author (name, gender, country) values ('Dode Knyvett', 'F', 'China');
insert into author (name, gender, country) values ('Joe Soitoux', 'M', 'Indonesia');
insert into author (name, gender, country) values ('Maurita Bengle', 'F', 'Azerbaijan');
insert into author (name, gender, country) values ('Hillyer Choat', 'M', 'Indonesia');
insert into author (name, gender, country) values ('Joya Allden', 'F', 'Japan');
insert into author (name, gender, country) values ('Muffin Cassedy', 'F', 'South Korea');
insert into author (name, gender, country) values ('Katrinka Ruffy', 'F', 'France');
insert into author (name, gender, country) values ('Valenka Alliberton', 'F', 'Portugal');
insert into author (name, gender, country) values ('Garrott Gooder', 'M', 'Portugal');
insert into author (name, gender, country) values ('Cynthy Gidman', 'F', 'Philippines');
insert into author (name, gender, country) values ('Ethyl Pawsey', 'F', 'Poland');
insert into author (name, gender, country) values ('Timmie Orpyne', 'M', 'Indonesia');
insert into author (name, gender, country) values ('Iona Withey', 'F', 'France');
insert into author (name, gender, country) values ('Bea Harvey', 'F', 'Iran');
insert into author (name, gender, country) values ('Morna Tonge', 'F', 'China');
insert into author (name, gender, country) values ('Lenci Downham', 'M', 'Malaysia');
insert into author (name, gender, country) values ('Deloris Matuszak', 'F', 'Japan');
insert into author (name, gender, country) values ('Kimbra Dommerque', 'F', 'Serbia');
insert into author (name, gender, country) values ('Hermina Drohane', 'F', 'China');
insert into author (name, gender, country) values ('Tansy Moody', 'F', 'Russia');
insert into author (name, gender, country) values ('Orsola Seely', 'F', 'United States');
insert into author (name, gender, country) values ('Allister Gellier', 'M', 'Colombia');
insert into author (name, gender, country) values ('Irene Charlet', 'F', 'Indonesia');
insert into author (name, gender, country) values ('Rafaellle Spira', 'M', 'Czech Republic');
insert into author (name, gender, country) values ('Kirsten Errey', 'F', 'Philippines');
insert into author (name, gender, country) values ('Willabella Favill', 'F', 'Netherlands');
insert into author (name, gender, country) values ('Chiarra Vader', 'F', 'China');
insert into author (name, gender, country) values ('Alessandra Robiou', 'F', 'Canada');
insert into author (name, gender, country) values ('Marlo Coffin', 'F', 'Portugal');
insert into author (name, gender, country) values ('Zared Giraldo', 'M', 'Sweden');
insert into author (name, gender, country) values ('Herold Luttgert', 'M', 'Philippines');
insert into author (name, gender, country) values ('Esme Upham', 'M', 'Portugal');
insert into author (name, gender, country) values ('Katharina Ramiro', 'F', 'China');
insert into author (name, gender, country) values ('Arie Deave', 'M', 'Samoa');
insert into author (name, gender, country) values ('Cos Shellshear', 'M', 'Portugal');
insert into author (name, gender, country) values ('Corliss Tilio', 'F', 'Portugal');
insert into author (name, gender, country) values ('Larina Hayer', 'F', 'Czech Republic');
insert into author (name, gender, country) values ('Nonna Britee', 'F', 'Mongolia');
insert into author (name, gender, country) values ('Carlita Goggan', 'F', 'China');
insert into author (name, gender, country) values ('Pat Jerman', 'M', 'Portugal');
insert into author (name, gender, country) values ('Orly Gullan', 'F', 'Russia');
insert into author (name, gender, country) values ('Winny Roscow', 'F', 'China');
insert into author (name, gender, country) values ('Dennie Jeffcock', 'M', 'Indonesia');
insert into author (name, gender, country) values ('Marys Tincknell', 'F', 'China');
insert into author (name, gender, country) values ('Ab Stollmeier', 'M', 'Philippines');
insert into author (name, gender, country) values ('Fredericka Braferton', 'F', 'Peru');
insert into author (name, gender, country) values ('Booth Bingell', 'M', 'Uzbekistan');
insert into author (name, gender, country) values ('Eilis Abrahmson', 'F', 'China');
insert into author (name, gender, country) values ('Haven Chadwin', 'M', 'Belgium');
insert into author (name, gender, country) values ('Seymour Butten', 'M', 'Greece');
insert into author (name, gender, country) values ('Bibbie Bubbins', 'F', 'Bosnia and Herzegovina');
insert into author (name, gender, country) values ('Mordecai Lyle', 'M', 'Sweden');
insert into author (name, gender, country) values ('Dyan Oret', 'F', 'France');
insert into author (name, gender, country) values ('Shaina Turner', 'F', 'United States');
insert into author (name, gender, country) values ('Carolyne Everist', 'F', 'Czech Republic');
insert into author (name, gender, country) values ('Darcy Mc Caughan', 'M', 'China');
insert into author (name, gender, country) values ('Helyn Tonna', 'F', 'China');
insert into author (name, gender, country) values ('Pansie Oloshkin', 'F', 'Czech Republic');
insert into author (name, gender, country) values ('Amery Sighard', 'M', 'Serbia');
insert into author (name, gender, country) values ('Betsy Lestor', 'F', 'Portugal');
insert into author (name, gender, country) values ('Sabra Kahn', 'F', 'Croatia');
insert into author (name, gender, country) values ('Loy Jackling', 'M', 'China');
insert into author (name, gender, country) values ('Maryjane Vicent', 'F', 'Philippines');
insert into author (name, gender, country) values ('Edyth Yeats', 'F', 'Finland');
insert into author (name, gender, country) values ('Terrill Manhood', 'M', 'Sweden');
insert into author (name, gender, country) values ('Carena Layne', 'F', 'China');
insert into author (name, gender, country) values ('Isabelita Cotter', 'F', 'Nigeria');
insert into author (name, gender, country) values ('Lammond Espinoy', 'M', 'Portugal');
insert into author (name, gender, country) values ('Shell Ollivier', 'M', 'Philippines');
insert into author (name, gender, country) values ('Mel Perillio', 'M', 'Costa Rica');
insert into author (name, gender, country) values ('Theodore Robker', 'M', 'Indonesia');
insert into author (name, gender, country) values ('Honey Asher', 'F', 'China');
insert into author (name, gender, country) values ('Myrna Heyward', 'F', 'Czech Republic');
insert into author (name, gender, country) values ('Brew Raubenheim', 'M', 'Mexico');
insert into author (name, gender, country) values ('Keriann Rossey', 'F', 'Mongolia');
insert into author (name, gender, country) values ('Donaugh Rainsbury', 'M', 'Mexico');
insert into author (name, gender, country) values ('Arv Zanassi', 'M', 'Somalia');
insert into author (name, gender, country) values ('Tallia Lowerson', 'F', 'China');
insert into author (name, gender, country) values ('Lilas Wootton', 'F', 'China');
insert into author (name, gender, country) values ('Marylynne Brane', 'F', 'Nigeria');
insert into author (name, gender, country) values ('Steven Parkman', 'M', 'Greece');
insert into author (name, gender, country) values ('Town Weins', 'M', 'Dominican Republic');
insert into author (name, gender, country) values ('Jeannette Malenfant', 'F', 'Russia');
insert into author (name, gender, country) values ('Friedrick Walesa', 'M', 'Colombia');
insert into author (name, gender, country) values ('Norma Schieferstein', 'F', 'Philippines');
insert into author (name, gender, country) values ('Miltie Venners', 'M', 'Russia');
insert into author (name, gender, country) values ('Westbrooke Crummey', 'M', 'China');
insert into author (name, gender, country) values ('Nicolais Wynett', 'M', 'United Kingdom');
insert into author (name, gender, country) values ('Blanche Cutler', 'F', 'Iran');
insert into author (name, gender, country) values ('Wainwright Phalip', 'M', 'Madagascar');
insert into author (name, gender, country) values ('Yehudi Dericot', 'M', 'China');
insert into author (name, gender, country) values ('Lorain Bartunek', 'F', 'Slovenia');
insert into author (name, gender, country) values ('Collete Pogue', 'F', 'Russia');
insert into author (name, gender, country) values ('Aurore Joslyn', 'F', 'Philippines');
insert into author (name, gender, country) values ('Vaughn MacKaig', 'M', 'Greece');
insert into author (name, gender, country) values ('Annis Robuchon', 'F', 'Russia');
insert into author (name, gender, country) values ('Nicki Witherington', 'F', 'Japan');
insert into author (name, gender, country) values ('Carey Bourges', 'F', 'United States');
insert into author (name, gender, country) values ('Nelle Smallridge', 'F', 'Philippines');
insert into author (name, gender, country) values ('Velvet Aps', 'F', 'Ukraine');
insert into author (name, gender, country) values ('Blakelee Hampton', 'F', 'Indonesia');
insert into author (name, gender, country) values ('Jada Tallyn', 'F', 'Philippines');
insert into author (name, gender, country) values ('Rosie Ceely', 'F', 'Indonesia');
insert into author (name, gender, country) values ('Niki Origan', 'M', 'Sweden');
insert into author (name, gender, country) values ('Nicholas Eccles', 'M', 'France');
insert into author (name, gender, country) values ('Tabitha Cutmere', 'F', 'China');
insert into author (name, gender, country) values ('Terza Allsworth', 'F', 'Ivory Coast');
insert into author (name, gender, country) values ('Waverley Stolz', 'M', 'Mayotte');
insert into author (name, gender, country) values ('Bent Seville', 'M', 'Haiti');
insert into author (name, gender, country) values ('Ethelred Klebes', 'M', 'Peru');
insert into author (name, gender, country) values ('Harry Needs', 'M', 'United States');
insert into author (name, gender, country) values ('Ravi Waples', 'M', 'United States');
insert into author (name, gender, country) values ('Rockwell Shafto', 'M', 'Sweden');
insert into author (name, gender, country) values ('Reuben Riccardelli', 'M', 'Ukraine');
insert into author (name, gender, country) values ('Janina Skewes', 'F', 'South Africa');
insert into author (name, gender, country) values ('Catlee Northcliffe', 'F', 'Bangladesh');
insert into author (name, gender, country) values ('Allayne Delamere', 'M', 'Greece');
insert into author (name, gender, country) values ('Marshal Bellin', 'M', 'Kenya');
insert into author (name, gender, country) values ('Vilma Kezor', 'F', 'France');
insert into author (name, gender, country) values ('Lani Wrigley', 'F', 'Venezuela');
insert into author (name, gender, country) values ('Alic Worts', 'M', 'Finland');
insert into author (name, gender, country) values ('Joanna Whitmarsh', 'F', 'Peru');
insert into author (name, gender, country) values ('Britta Paulsson', 'F', 'Brazil');
insert into author (name, gender, country) values ('Leanna Senior', 'F', 'China');
insert into author (name, gender, country) values ('Daryn Wookey', 'F', 'China');
insert into author (name, gender, country) values ('Lazare Bimson', 'M', 'China');
insert into author (name, gender, country) values ('Gal Stollenwerck', 'M', 'China');
insert into author (name, gender, country) values ('Aldridge Commin', 'M', 'Ecuador');
insert into author (name, gender, country) values ('Cos Bilt', 'M', 'China');
insert into author (name, gender, country) values ('Ellswerth Townley', 'M', 'Macedonia');
insert into author (name, gender, country) values ('Alisander Beuscher', 'M', 'Poland');
insert into author (name, gender, country) values ('Rhys Harling', 'M', 'Palestinian Territory');
insert into author (name, gender, country) values ('Cilka Brightwell', 'F', 'Palestinian Territory');
insert into author (name, gender, country) values ('Jorry Robinson', 'F', 'China');
insert into author (name, gender, country) values ('Wilhelmine Haller', 'F', 'Nigeria');
insert into author (name, gender, country) values ('Teressa Mauvin', 'F', 'China');
insert into author (name, gender, country) values ('Anissa MacGorman', 'F', 'Indonesia');
insert into author (name, gender, country) values ('Devinne Heaton', 'F', 'China');
insert into author (name, gender, country) values ('Abdel Couth', 'M', 'Syria');
insert into author (name, gender, country) values ('Eugenia Gaitskell', 'F', 'Ukraine');
insert into author (name, gender, country) values ('Halie Courtin', 'F', 'South Africa');
insert into author (name, gender, country) values ('Balduin Zmitrichenko', 'M', 'Portugal');
insert into author (name, gender, country) values ('Benn Castelluzzi', 'M', 'China');
insert into author (name, gender, country) values ('Sayers Swinden', 'M', 'Mongolia');
insert into author (name, gender, country) values ('Corrie Riddick', 'M', 'Indonesia');
insert into author (name, gender, country) values ('Phoebe Foltin', 'F', 'Brazil');
insert into author (name, gender, country) values ('Trent Spare', 'M', 'China');
insert into author (name, gender, country) values ('Birgit Dies', 'F', 'Indonesia');
insert into author (name, gender, country) values ('Hope Godsmark', 'F', 'Peru');
insert into author (name, gender, country) values ('Persis Lanon', 'F', 'Poland');
insert into author (name, gender, country) values ('Hector Orbell', 'M', 'Philippines');
insert into author (name, gender, country) values ('Vinita Mouton', 'F', 'Russia');
insert into author (name, gender, country) values ('Hermia Mole', 'F', 'Canada');
insert into author (name, gender, country) values ('Alexis Smeeton', 'F', 'Armenia');
insert into author (name, gender, country) values ('Lanie Thring', 'F', 'Russia');
insert into author (name, gender, country) values ('Ricki Arpur', 'M', 'Finland');
insert into author (name, gender, country) values ('Bernelle Davydychev', 'F', 'El Salvador');
insert into author (name, gender, country) values ('Gene Nestoruk', 'F', 'China');
insert into author (name, gender, country) values ('Rosene Maciak', 'F', 'Poland');
insert into author (name, gender, country) values ('Radcliffe Moodie', 'M', 'Colombia');
insert into author (name, gender, country) values ('Inger Rilston', 'M', 'France');
insert into author (name, gender, country) values ('Binny Von Der Empten', 'F', 'Macedonia');
insert into author (name, gender, country) values ('Kacie Massenhove', 'F', 'Nicaragua');
insert into author (name, gender, country) values ('Arin Meah', 'M', 'Poland');
insert into author (name, gender, country) values ('Mauricio Scothern', 'M', 'Russia');
insert into author (name, gender, country) values ('Roxine Bartelot', 'F', 'Solomon Islands');
